lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # Vérifiez que cette variable d'environnement est bien définie
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # Vérifiez que cette variable d'environnement est bien définie
    pass_phrase: '%env(JWT_PASSPHRASE)%'        # Vérifiez que cette variable d'environnement est bien définie
    token_ttl: 3600
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: security.credentials.password
